<?php $email = get_theme_mod('wish_email', 'info@wishcandle.shop'); $phone = get_theme_mod('wish_phone', '+972 553 161 567'); ?>
<footer>
  <div class="footer-top"><a class="brand-wordmark footer-wordmark" href="<?php echo esc_url(home_url('/')); ?>" aria-label="Wish Candle home"><strong>WISH</strong><small>soy candle</small></a><div class="footer-socials"><div class="icons"><a href="<?php echo esc_url(get_theme_mod('wish_facebook', '#')); ?>" aria-label="Facebook">f</a><a href="<?php echo esc_url(get_theme_mod('wish_instagram', '#')); ?>" aria-label="Instagram">i</a></div><span>Our social networks</span></div></div>
  <div class="footer-main"><div class="footer-columns">
    <div class="footer-col"><h3>Shop</h3><?php wp_nav_menu(['theme_location'=>'footer_shop','container'=>false,'items_wrap'=>'<ul class="footer-menu">%3$s</ul>','fallback_cb'=>false]); ?></div>
    <div class="footer-col"><h3>Online store</h3><a href="<?php echo esc_url(home_url('/')); ?>">Home</a><a href="<?php echo esc_url(home_url('/about/')); ?>">About us</a><a href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/shop/')); ?>">Shop</a><a href="<?php echo esc_url(home_url('/wholesale/')); ?>">Wholesales</a></div>
    <div class="footer-col"><h3>Support</h3><?php wp_nav_menu(['theme_location'=>'footer_support','container'=>false,'items_wrap'=>'<ul class="footer-menu">%3$s</ul>','fallback_cb'=>false]); ?></div>
    <div class="footer-col"><h3>Contacts and Working hours</h3><p><?php echo esc_html(get_theme_mod('wish_address', 'Karl Popper 5, Netanya, Israel')); ?></p><a href="mailto:<?php echo esc_attr($email); ?>"><?php echo esc_html($email); ?></a><a href="tel:<?php echo esc_attr(preg_replace('/[^+0-9]/', '', $phone)); ?>"><?php echo esc_html($phone); ?></a><br><p><strong>Every day:</strong> 08:00 – 20:00</p></div>
  </div><div class="newsletter"><h3>Receive exclusive offers by subscribing to our newsletter</h3><form class="newsletter-form" data-newsletter><input type="email" aria-label="Email" placeholder="EMAIL" required><button type="submit">Subscribe</button></form><p class="privacy-note">By clicking the button, you consent to the processing of personal data and agree to the privacy policy</p><p class="newsletter-status" aria-live="polite"></p></div></div>
  <div class="footer-bottom"><div class="payments"><span class="payment">VISA</span><span class="payment">Mastercard</span><span class="payment">PayPal</span><span class="payment">Apple Pay</span></div><span>© <?php echo esc_html(date('Y')); ?> Wish Candle</span></div>
</footer><div class="toast" id="toast" role="status" aria-live="polite"></div><?php wp_footer(); ?></body></html>
